### ISSUE TITLE
Page connection timeout

### ISSUE THREAD

**Issue by vladimircastrosv** [telppa/Translation-Terminator#1]
Hi, I'm getting this error when the application is initialized. 
![image](https://user-images.githubusercontent.com/82183028/225776568-1e8fae86-3f27-424e-98ec-c0ae5566d5da.png)

![image](https://user-images.githubusercontent.com/82183028/225776489-136954f0-14bf-4922-8661-a6bc5af7e3aa.png)

**Comment by vladimircastrosv** [comment]
I was able to fixed it myself, I just had to replace Chrome.ahk with the official library and its dependencies.

**Comment by vladimircastrosv** [comment]
Apparently it was not an issue in the Chorme.ahk or deperencies.

**Comment by hmirror123** [comment]
谢谢，我也遇到了同样问题
